- name: Create Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC Setup Variable
      include_vars: vars/output_vars

    - name: Create vprofile EC2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - debug:
        var: key_out

  #  - name: Save private key into file bastion-key.pem
   #   ansible.builtin.copy:
    #    content: "{{key_out.key.private_key}}"
     #   dest: "./bastion-key.pem"
      #  mode: 0600
     # when: key_out.changed


    - name: Create Security Group for Bastion Host
      ec2_group:
        name: BastionHostSG
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - name: Create Bastion Host
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "Bastion Host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        security_group: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out




