- name: Create Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC Setup Variable
      include_vars: vars/output_setup

    - name: Create vprofile EC2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    -  debug:
         var: key_out



