- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        aws_region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout

#    - debug:
#        var: vpcout

    - name: Create Public Subnet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out



