- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        aws_region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout



